version: '1.0'

networks:
  airflow-tier:
    external: true

services:
  dbt:
    image: dbt
    container_name: dbt
    networks:
      - airflow-tier
    restart: always
    ports:
      - "8080:8080"
    command: >
      bash -c "cd sample_project &&
               dbt seed  --target postgres_test &&
               dbt run  --target postgres_test &&
               dbt docs generate  --target postgres_test &&
               dbt docs serve  --target postgres_test --host 0.0.0.0 --port 8080"
    volumes:
      - /usr/data_archt/python_module:/app/python_module
      - /usr/data_archt/dbt/image/sample_project:/app/sample_project