version: '1.0'

networks:
  airflow-tier:
    driver: bridge

services:
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - airflow-tier
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

volumes:
  redis_data