version: '1.0'

networks:
  airflow-tier:
    external: true

services:
  mlflow:
    image: mlflow
    container_name: mlflow
    networks:
      - airflow-tier
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://postgres:Aa123456@postgres:5432/postgres
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - /usr/data_archt/python_module:/mlflow/python_module
      - /usr/data_archt/mlflow/image/sample_project:/mlflow/sample_project
    command: ["mlflow", "server", "--host", "0.0.0.0"]